utils::globalVariables(c(
  ".tx",
  "id",
  "rarity",
  "trigger_phase",
  "career_min",
  "tags",
  "model_family_affinity",
  "mascot_state_affinity",
  "combo_chain",
  "text",
  "weight",
  "weight_recency",
  "weight_combo",
  "weight_final",
  # ggplot2 aesthetic columns referenced inside aes()
  "x",
  "y"
))
